[project]
name = "jcs"
version = "0.1.0"
description = "JCS AI bot"
requires-python = ">=3.8"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pytest",
    "ruff",
    "mypy","python-dotenv",
]

[project.scripts]
start = "uvicorn app.main:app --reload"
